export const DATA_FETCH_REQUEST = 'DATA_FETCH_REQUEST'
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS'
export const DATA_FETCH_FAILURE = 'DATA_FETCH_FAILURE'
export const INDEX_FETCH = 'INDEX_FETCH_CALL'